In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load dataset
data_path = 'Customer Churn Prediction Dataset/Churn_Modelling.csv'
df = pd.read_csv(data_path)

# Display first few rows
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [2]:
# Drop columns that are not useful for prediction
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True, errors='ignore')

# Check for missing values
print('Missing values in each column:')
print(df.isnull().sum())

# Encode categorical variables
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

# One-hot encode Geography
df = pd.get_dummies(df, columns=['Geography'], drop_first=True)

# Features and target
X = df.drop('Exited', axis=1)
y = df['Exited']

# Feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

Missing values in each column:
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [3]:
def train_evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    cr = classification_report(y_test, y_pred)
    print(f"Model: {model.__class__.__name__}")
    print(f"Accuracy: {acc:.4f}")
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(cr)
    print("-----------------------------------")
    return acc

# Logistic Regression
logreg = LogisticRegression(random_state=42, max_iter=1000)
acc_logreg = train_evaluate_model(logreg, X_train, X_test, y_train, y_test)

# Random Forest
rf = RandomForestClassifier(random_state=42)
acc_rf = train_evaluate_model(rf, X_train, X_test, y_train, y_test)

# Gradient Boosting
gb = GradientBoostingClassifier(random_state=42)
acc_gb = train_evaluate_model(gb, X_train, X_test, y_train, y_test)

# Compare model accuracies
accuracies = {'Logistic Regression': acc_logreg, 'Random Forest': acc_rf, 'Gradient Boosting': acc_gb}
best_model_name = max(accuracies, key=accuracies.get)
print(f"Best performing model: {best_model_name} with accuracy {accuracies[best_model_name]:.4f}")

Model: LogisticRegression
Accuracy: 0.8110
Confusion Matrix:
[[1543   64]
 [ 314   79]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

-----------------------------------
Model: RandomForestClassifier
Accuracy: 0.8660
Confusion Matrix:
[[1552   55]
 [ 213  180]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.77      0.46      0.57       393

    accuracy                           0.87      2000
   macro avg       0.82      0.71      0.75      2000
weighted avg       0.86      0.87      0.85      2000

-----------------------------------
Model: GradientBoostingClassifier
Accuracy: 0.8675
Confusion Matrix:
[[1543   64]
 [ 201  192]]
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000

-----------------------------------
Best performing model: Gradient Boosting with accuracy 0.8675